# 
# YAML init file for SNAP microservice framework
#
#

globals:
        bind_host:                   127.0.0.1
        port:                        5000
        debug:                       True
        logfile:                     sentinel.log
        project_directory:           $SENTINEL_HOME
        transform_function_module:   s_transforms
        service_module:              s_services 
        preprocessor_module:         s_decode


service_objects:
        test_service:
                class: TestServiceObject
                init_params:
                        - name: host
                          value: localhost

        gcloud_config:
                class: GoogleCloudConfigService
                init_params:
                        - name: PUBSUB_VERIFICATION_TOKEN
                          value: $PUBSUB_VERIFICATION_TOKEN

                        - name: PUBSUB_TOPIC
                          value: $PUBSUB_TOPIC

                        - name: PROJECT
                          value: $GC_PROJECT

data_shapes:
        default:
                fields:

        event:
                fields:
                        - name: token
                          datatype: string
                          required: True
                        - name: message
                          datatype: string
                          required: True
        test_shape:
                fields:
                        - name: placeholder
                          datatype: string
                          required: True
                        - name: day
                          datatype: string
                          required: True


transforms:
        ping:
            route:              /ping
            method:             GET
            input_shape:        default
            output_mimetype:    application/json
            
        test:
            route:              /test
            method:             GET
            input_shape:        test_shape
            output_mimetype:    application/json

        pubsub_push:
            route:              /pubsub/push
            method:             POST
            input_shape:        event
            output_mimetype:    application/json

        pubsub_push_alt:
            route:              /_ah/push-handlers/test
            method:             POST
            input_shape:        event
            output_mimetype:    application/json

        noop:
            route:              /
            method:             POST
            input_shape:        default
            output_mimetype:    application/json

        noop_get:
            route:              /
            method:             GET
            input_shape:        default
            output_mimetype:    application/json



error_handlers:
        - error:                NoSuchObjectException
          tx_status_code:       HTTP_NOT_FOUND 
                
        - error:                DuplicateIDException
          tx_status_code:       HTTP_BAD_REQUEST